spring:
  application:
    name: pick-eat-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pick_eat}
    username: ${DB_USERNAME:${user.name}}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

google:
  places:
    api-key: ${GOOGLE_PLACES_API_KEY:}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
