CREATE TABLE discovery_spots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code    VARCHAR(30) NOT NULL,
    region_name    VARCHAR(50) NOT NULL,
    display_order  INTEGER NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT discovery_spots_region_code_unique UNIQUE (region_code),
    CONSTRAINT discovery_spots_display_order_unique UNIQUE (display_order),
    CONSTRAINT discovery_spots_region_code_not_blank CHECK (LENGTH(TRIM(region_code)) > 0),
    CONSTRAINT discovery_spots_region_name_not_blank CHECK (LENGTH(TRIM(region_name)) > 0),
    CONSTRAINT discovery_spots_display_order_positive CHECK (display_order > 0)
);

CREATE TABLE discovery_spot_restaurants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discovery_spot_id BIGINT NOT NULL,
    restaurant_id   BIGINT NOT NULL,
    display_order   INTEGER NOT NULL,
    one_line_intro  VARCHAR(200) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT discovery_spot_restaurants_spot_fk
        FOREIGN KEY (discovery_spot_id) REFERENCES discovery_spots (id) ON DELETE CASCADE,
    CONSTRAINT discovery_spot_restaurants_restaurant_fk
        FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE RESTRICT,
    CONSTRAINT discovery_spot_restaurants_spot_restaurant_unique
        UNIQUE (discovery_spot_id, restaurant_id),
    CONSTRAINT discovery_spot_restaurants_spot_order_unique
        UNIQUE (discovery_spot_id, display_order),
    CONSTRAINT discovery_spot_restaurants_display_order_range
        CHECK (display_order BETWEEN 1 AND 5),
    CONSTRAINT discovery_spot_restaurants_intro_not_blank
        CHECK (LENGTH(TRIM(one_line_intro)) > 0)
);

CREATE INDEX discovery_spot_restaurants_restaurant_idx
    ON discovery_spot_restaurants (restaurant_id);

INSERT INTO discovery_spots (region_code, region_name, display_order)
VALUES
    ('SINSA', '신사', 1),
    ('HYEHWA', '혜화', 2),
    ('SEOCHEON', '서촌', 3),
    ('HANNAM', '한남', 4),
    ('JONGNO', '종로', 5)
ON CONFLICT (region_code) DO UPDATE SET
    region_name = EXCLUDED.region_name,
    display_order = EXCLUDED.display_order,
    updated_at = CURRENT_TIMESTAMP;

COMMENT ON TABLE discovery_spots IS '초기 홈 탐색 화면에 노출하는 운영자 선정 고정 지역';
COMMENT ON TABLE discovery_spot_restaurants IS '탐색 지역별 운영자 선정 식당과 고정 노출 순서';
COMMENT ON COLUMN discovery_spot_restaurants.one_line_intro IS '탐색 카드에 표시할 운영자 작성 한 줄 소개';
