CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    food_category VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT restaurants_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
    CONSTRAINT restaurants_latitude_range CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT restaurants_longitude_range CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT restaurants_address_not_blank
        CHECK (address IS NULL OR LENGTH(TRIM(address)) > 0),
    CONSTRAINT restaurants_food_category_not_blank
        CHECK (food_category IS NULL OR LENGTH(TRIM(food_category)) > 0)
);

COMMENT ON TABLE restaurants IS '팀이 확보한 식당 원본 자료를 정리하여 저장하는 식당 정보';
COMMENT ON COLUMN restaurants.address IS '미확인 주소는 NULL로 저장';
COMMENT ON COLUMN restaurants.latitude IS 'WGS84 위도';
COMMENT ON COLUMN restaurants.longitude IS 'WGS84 경도';
COMMENT ON COLUMN restaurants.food_category IS '대표 음식 분류. 미분류는 NULL로 저장';
COMMENT ON COLUMN restaurants.updated_at IS '생성 시 기본값 적용. 수정 시 애플리케이션에서 갱신';
