-- 폐업·정보 오류 신고. 사용자가 신고하면 PENDING으로 쌓이고, 운영자가 확인한 뒤
-- 받아들이면(ACCEPTED) 식당에 excluded_at을 찍어 추천 후보에서 뺀다. 검토 절차는 docs/OPERATIONS.md 참고.
ALTER TABLE restaurants
    ADD COLUMN excluded_at TIMESTAMPTZ,
    ADD COLUMN excluded_reason VARCHAR(200);

COMMENT ON COLUMN restaurants.excluded_at IS '운영자가 추천 후보에서 뺀 시각(폐업 확인 등). NULL이면 추천 대상';
COMMENT ON COLUMN restaurants.excluded_reason IS '추천 후보에서 뺀 이유(운영 메모)';

CREATE TABLE restaurant_reports (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id     BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    reason        VARCHAR(30) NOT NULL,
    detail        VARCHAR(300),
    status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at   TIMESTAMPTZ,

    CONSTRAINT restaurant_reports_member_fk
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT restaurant_reports_restaurant_fk
        FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE,
    CONSTRAINT restaurant_reports_reason_check
        CHECK (reason IN ('CLOSED', 'WRONG_INFO', 'WRONG_CATEGORY', 'OTHER')),
    CONSTRAINT restaurant_reports_status_check
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

-- 같은 사람이 같은 식당을 검토 전에 여러 번 신고하지 못하게 한다. 검토가 끝나면 다시 신고할 수 있다.
CREATE UNIQUE INDEX restaurant_reports_pending_unique_idx
    ON restaurant_reports (member_id, restaurant_id)
    WHERE status = 'PENDING';

CREATE INDEX restaurant_reports_status_idx ON restaurant_reports (status, created_at);

COMMENT ON TABLE restaurant_reports IS '사용자 식당 신고(폐업·정보 오류). 운영자가 수동 검토한다';
