CREATE TABLE IF NOT EXISTS restaurants (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_provider               VARCHAR(20) NOT NULL DEFAULT 'GOOGLE',
    google_place_id             VARCHAR(255),
    name                        VARCHAR(200) NOT NULL,
    food_category               VARCHAR(30),
    address                     VARCHAR(500),
    latitude                    DOUBLE PRECISION NOT NULL,
    longitude                   DOUBLE PRECISION NOT NULL,
    phone_number                VARCHAR(50),
    opening_hours_text          TEXT,
    external_rating             NUMERIC(2, 1),
    external_rating_count       INTEGER,
    price_level                 VARCHAR(30),
    representative_image_url    VARCHAR(1000),
    external_data_refreshed_at  TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT restaurants_name_not_blank CHECK (LENGTH(TRIM(name)) > 0),
    CONSTRAINT restaurants_provider_not_blank CHECK (LENGTH(TRIM(data_provider)) > 0),
    CONSTRAINT restaurants_place_id_not_blank
        CHECK (google_place_id IS NULL OR LENGTH(TRIM(google_place_id)) > 0),
    CONSTRAINT restaurants_latitude_range CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT restaurants_longitude_range CHECK (longitude BETWEEN -180 AND 180),
    CONSTRAINT restaurants_external_rating_range
        CHECK (external_rating IS NULL OR external_rating BETWEEN 0 AND 5),
    CONSTRAINT restaurants_external_rating_count_non_negative
        CHECK (external_rating_count IS NULL OR external_rating_count >= 0),
    CONSTRAINT restaurants_food_category
        CHECK (food_category IS NULL OR food_category IN (
            'KOREAN', 'JAPANESE', 'CHINESE', 'WESTERN', 'CAFE_DESSERT'
        ))
);

-- develop 브랜치의 V1으로 이미 생성된 DB도 데이터 손실 없이 현재 스키마로 맞춘다.
ALTER TABLE restaurants
    ADD COLUMN IF NOT EXISTS data_provider VARCHAR(20) NOT NULL DEFAULT 'GOOGLE',
    ADD COLUMN IF NOT EXISTS google_place_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50),
    ADD COLUMN IF NOT EXISTS opening_hours_text TEXT,
    ADD COLUMN IF NOT EXISTS external_rating NUMERIC(2, 1),
    ADD COLUMN IF NOT EXISTS external_rating_count INTEGER,
    ADD COLUMN IF NOT EXISTS price_level VARCHAR(30),
    ADD COLUMN IF NOT EXISTS representative_image_url VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS external_data_refreshed_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS restaurants_google_place_id_unique_idx
    ON restaurants (google_place_id)
    WHERE google_place_id IS NOT NULL;

COMMENT ON TABLE restaurants IS 'Pick Eat 추천 및 Pick 기록에서 사용하는 식당 정보';
COMMENT ON COLUMN restaurants.data_provider IS '외부 장소 데이터 공급자 또는 CURATED';
COMMENT ON COLUMN restaurants.google_place_id IS 'Google Places 식당 식별자';
COMMENT ON COLUMN restaurants.external_rating IS '외부 공급자의 사용자 평점';
COMMENT ON COLUMN restaurants.external_rating_count IS '외부 공급자의 평가 수';
COMMENT ON COLUMN restaurants.external_data_refreshed_at IS '외부 장소 정보를 마지막으로 갱신한 시각';
